### PR TITLE
Fix retrieve context

### LINKED ISSUE #73: Fix retrieve context
The retrieve context is not working on mobile because the socket listeners aren't init before the socker server event 'connection' that we're using to sync the new coming session mtv room context. Atm on browser it seems to be working, but it's quite random.

The solution is to stop using the server socket connection event to synchronize the session. But thanks to an invoke in the state machine first initial state, where we emit as a bottle in the sea a GET_CONTEXT event.
If it occurs in the back that the socket is related to an existing mtvroom then the server will emit to this socket a RETRIEVE_CONTEXT event that will be catch by the state machine at its root level.
We do not use callback as it make the state machine goes crazy and infinite looping on it's initialization

### PR DESCRIPTION
**Pull request by prastoin**
close #73

### CODE REVIEW

**Comment by prastoin** [comment]
close #73

**Comment by Devessier** [comment]
Great. The bug was difficult to spot.
We can merge.

**Review by Devessier — COMMENTED** [review]
Great. The bug was difficult to spot.
We can merge.

**Review by Devessier — APPROVED** [review]
We can merge.

**Pull request merged**
