### PR TITLE
Add Pull to refresh to MPE Library

### PR DESCRIPTION
**Pull request by Devessier**
Closes https://github.com/AdonisEnProvence/MusicRoom/issues/387

Must be reviewed **after** https://github.com/AdonisEnProvence/MusicRoom/pull/394.

### CODE REVIEW

**Comment by prastoin** [comment]
This is a great idea !
I was wondering if we would have to implem the refresh on every of our infinite loading search engine screen ?

**Review by prastoin — APPROVED** [review]
Huge job done
One question pending before mergin but 100% approved
Ready to be merged

**Comment by Devessier** [comment]
I think this is not _necessary_ for other searches because, Library screen is mounted from the beginning of the application, and is never unmounted.
Other searches are meant to be used once, and are then unmounted. Therefore, on the next mounting, the results would have been cleared.

Although, this feature can be implemented for any other search. I just think it's not necessary for our current expectations.

**Comment by prastoin** [comment]
I agree !

**Pull request merged**
